# For more information: https://laravel.com/docs/sail
version: '3'
services:
    sams:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        labels:
            - traefik.enable=true
            - traefik.docker.network=docker
            - traefik.http.routers.sams.entrypoints=http,https
            - traefik.http.routers.sams.rule=Host(`sams.this.lan`) # You can use any domain allowed by your TLS certificate
            - traefik.http.routers.sams.tls=true
            - traefik.http.routers.sams.service=sams@docker
            - traefik.http.services.sams.loadbalancer.server.port=80 # Adapt to the exposed port in the service
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - docker
networks:
    sail:
       driver: bridge
    docker:
       external: true
